import type { Recipe } from "@/lib/mealplanner/types";

export const recipes: Recipe[] = [
  // Breakfast (7)
  {
    id: "b-overnight-oats-berry",
    mealType: "breakfast",
    name: "Overnight oats met bessen",
    calories: 420,
    protein: 28,
    carbs: 55,
    fat: 10,
    ingredients: ["60g havermout", "200ml (soja)melk", "150g bessen", "15g chiazaad", "1 tl kaneel"],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["vegetarian", "high_protein"],
    allergens: ["gluten", "soy"],
  },
  {
    id: "b-greek-yogurt-granola",
    mealType: "breakfast",
    name: "Griekse yoghurt bowl",
    calories: 380,
    protein: 32,
    carbs: 40,
    fat: 9,
    ingredients: ["250g Griekse yoghurt", "30g granola", "1 banaan", "1 tl honing"],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["vegetarian", "high_protein"],
    allergens: ["lactose", "gluten"],
  },
  {
    id: "b-eggs-toast-avocado",
    mealType: "breakfast",
    name: "Roerei + volkoren toast + avocado",
    calories: 460,
    protein: 26,
    carbs: 36,
    fat: 22,
    ingredients: ["3 eieren", "2 sneetjes volkoren brood", "1/2 avocado", "peper & zout"],
    suitable_for: ["muscle", "maintenance"],
    tags: ["vegetarian", "high_protein"],
    allergens: ["egg", "gluten"],
  },
  {
    id: "b-protein-smoothie",
    mealType: "breakfast",
    name: "Proteïne smoothie (banaan + pindakaas)",
    calories: 520,
    protein: 40,
    carbs: 50,
    fat: 18,
    ingredients: ["1 banaan", "250ml (soja)melk", "30g proteïnepoeder", "15g pindakaas", "ijsblokjes"],
    suitable_for: ["muscle", "maintenance"],
    tags: ["vegetarian", "high_protein"],
    allergens: ["nuts", "soy", "lactose"],
  },
  {
    id: "b-cottage-cheese-fruit",
    mealType: "breakfast",
    name: "Hüttenkäse met fruit",
    calories: 340,
    protein: 30,
    carbs: 32,
    fat: 8,
    ingredients: ["250g hüttenkäse", "1 appel of peer", "1 tl kaneel", "10g walnoten (optioneel)"],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["vegetarian", "high_protein"],
    allergens: ["lactose", "nuts"],
  },
  {
    id: "b-vegan-tofu-scramble",
    mealType: "breakfast",
    name: "Tofu scramble met groenten",
    calories: 390,
    protein: 26,
    carbs: 24,
    fat: 20,
    ingredients: ["200g tofu", "paprika", "spinazie", "kurkuma", "1 tl olijfolie"],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["vegan", "vegetarian", "high_protein", "gluten_free", "lactose_free"],
    allergens: ["soy"],
  },
  {
    id: "b-rice-cakes-quark",
    mealType: "breakfast",
    name: "Rijstwafels met magere kwark",
    calories: 360,
    protein: 32,
    carbs: 44,
    fat: 6,
    ingredients: ["4 rijstwafels", "250g magere kwark", "aardbeien", "1 tl honing"],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["vegetarian", "high_protein", "gluten_free"],
    allergens: ["lactose"],
  },

  // Lunch (9)
  {
    id: "l-chicken-wrap",
    mealType: "lunch",
    name: "Kip wrap + groentemix",
    calories: 540,
    protein: 42,
    carbs: 55,
    fat: 16,
    ingredients: ["2 wraps", "180g kipfilet", "sla", "tomaat", "komkommer", "yoghurtsaus"],
    suitable_for: ["muscle", "maintenance"],
    tags: ["high_protein"],
    allergens: ["gluten", "lactose"],
  },
  {
    id: "l-tuna-salad-bowl",
    mealType: "lunch",
    name: "Tonijnsalade bowl",
    calories: 480,
    protein: 40,
    carbs: 35,
    fat: 18,
    ingredients: ["1 blik tonijn", "gemengde sla", "cherrytomaat", "maïs", "1 el olijfolie", "citroen"],
    suitable_for: ["weight_loss", "maintenance"],
    tags: ["gluten_free", "lactose_free", "high_protein"],
    allergens: ["fish"],
  },
  {
    id: "l-veggie-burrito-bowl",
    mealType: "lunch",
    name: "Veggie burrito bowl",
    calories: 560,
    protein: 28,
    carbs: 78,
    fat: 14,
    ingredients: ["150g rijst", "150g kidneybonen", "paprika", "ui", "tomaat", "kruidenmix"],
    suitable_for: ["weight_loss", "maintenance"],
    tags: ["vegan", "vegetarian", "gluten_free", "lactose_free"],
    allergens: [],
  },
  {
    id: "l-turkey-sandwich",
    mealType: "lunch",
    name: "Volkoren sandwich met kalkoen",
    calories: 510,
    protein: 38,
    carbs: 52,
    fat: 14,
    ingredients: ["3 sneetjes volkoren brood", "120g kalkoenfilet", "mosterd", "sla", "tomaat"],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["high_protein"],
    allergens: ["gluten"],
  },
  {
    id: "l-salmon-quinoa",
    mealType: "lunch",
    name: "Zalm + quinoa + groenten",
    calories: 620,
    protein: 42,
    carbs: 55,
    fat: 24,
    ingredients: ["150g zalm", "120g quinoa", "broccoli", "citroen", "1 tl olijfolie"],
    suitable_for: ["muscle", "maintenance"],
    tags: ["gluten_free", "lactose_free", "high_protein"],
    allergens: ["fish"],
  },
  {
    id: "l-egg-salad",
    mealType: "lunch",
    name: "Eiersalade + crackers",
    calories: 520,
    protein: 26,
    carbs: 40,
    fat: 26,
    ingredients: ["3 eieren", "2 el (light) mayo", "crackers", "sla", "paprika"],
    suitable_for: ["maintenance"],
    tags: ["vegetarian", "high_protein"],
    allergens: ["egg", "gluten"],
  },
  {
    id: "l-lentil-soup",
    mealType: "lunch",
    name: "Linzen soep + volkoren brood",
    calories: 520,
    protein: 26,
    carbs: 78,
    fat: 10,
    ingredients: ["linzen", "wortel", "ui", "selder", "bouillon", "2 sneetjes volkoren brood"],
    suitable_for: ["weight_loss", "maintenance"],
    tags: ["vegan", "vegetarian"],
    allergens: ["gluten"],
  },
  {
    id: "l-chicken-rice-salad",
    mealType: "lunch",
    name: "Kip + rijstsalade",
    calories: 590,
    protein: 44,
    carbs: 70,
    fat: 14,
    ingredients: ["180g kipfilet", "150g rijst", "komkommer", "tomaat", "citroen", "kruiden"],
    suitable_for: ["muscle", "maintenance"],
    tags: ["gluten_free", "lactose_free", "high_protein"],
    allergens: [],
  },
  {
    id: "l-vegan-chickpea-salad",
    mealType: "lunch",
    name: "Kikkererwten salade + avocado",
    calories: 580,
    protein: 22,
    carbs: 62,
    fat: 26,
    ingredients: ["kikkererwten", "avocado", "tomaat", "komkommer", "citroen", "kruiden"],
    suitable_for: ["maintenance"],
    tags: ["vegan", "vegetarian", "gluten_free", "lactose_free"],
    allergens: [],
  },

  // Dinner (9)
  {
    id: "d-steak-veggies",
    mealType: "dinner",
    name: "Biefstuk + groene groenten",
    calories: 560,
    protein: 46,
    carbs: 18,
    fat: 32,
    ingredients: ["180g biefstuk", "boontjes", "sla of broccoli", "1 tl olijfolie", "kruiden"],
    suitable_for: ["muscle", "maintenance"],
    tags: ["gluten_free", "lactose_free", "high_protein"],
    allergens: [],
  },
  {
    id: "d-chicken-stir-fry",
    mealType: "dinner",
    name: "Kip roerbak met groenten",
    calories: 520,
    protein: 44,
    carbs: 26,
    fat: 24,
    ingredients: ["200g kipfilet", "wokgroenten", "sojasaus", "1 el sesamolie", "knoflook"],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["high_protein", "lactose_free"],
    allergens: ["soy"],
  },
  {
    id: "d-salmon-asparagus",
    mealType: "dinner",
    name: "Zalm + asperges",
    calories: 540,
    protein: 40,
    carbs: 14,
    fat: 34,
    ingredients: ["170g zalm", "asperges", "citroen", "1 tl olijfolie", "dille"],
    suitable_for: ["weight_loss", "maintenance"],
    tags: ["gluten_free", "lactose_free", "high_protein"],
    allergens: ["fish"],
  },
  {
    id: "d-turkey-chili",
    mealType: "dinner",
    name: "Kalkoen chili (zonder rijst)",
    calories: 510,
    protein: 44,
    carbs: 34,
    fat: 20,
    ingredients: ["200g kalkoengehakt", "tomatenblokjes", "kidneybonen", "paprika", "ui", "kruiden"],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["gluten_free", "lactose_free", "high_protein"],
    allergens: [],
  },
  {
    id: "d-tofu-curry",
    mealType: "dinner",
    name: "Tofu curry + bloemkoolrijst",
    calories: 490,
    protein: 28,
    carbs: 28,
    fat: 26,
    ingredients: ["200g tofu", "curry pasta", "kokosmelk light", "wokgroenten", "bloemkoolrijst"],
    suitable_for: ["weight_loss", "maintenance"],
    tags: ["vegan", "vegetarian", "gluten_free", "lactose_free"],
    allergens: ["soy"],
  },
  {
    id: "d-omelet-veggies",
    mealType: "dinner",
    name: "Omelet met groenten",
    calories: 420,
    protein: 32,
    carbs: 16,
    fat: 26,
    ingredients: ["4 eieren", "champignons", "spinazie", "ui", "1 tl olijfolie"],
    suitable_for: ["weight_loss", "maintenance"],
    tags: ["vegetarian", "gluten_free", "high_protein"],
    allergens: ["egg"],
  },
  {
    id: "d-cod-zoodles",
    mealType: "dinner",
    name: "Kabeljauw + courgetti",
    calories: 460,
    protein: 42,
    carbs: 18,
    fat: 22,
    ingredients: ["200g kabeljauw", "courgette", "tomatensaus", "knoflook", "1 tl olijfolie"],
    suitable_for: ["weight_loss", "maintenance"],
    tags: ["gluten_free", "lactose_free", "high_protein"],
    allergens: ["fish"],
  },
  {
    id: "d-chicken-salad",
    mealType: "dinner",
    name: "Kip salade (grote portie)",
    calories: 480,
    protein: 46,
    carbs: 20,
    fat: 22,
    ingredients: ["220g kipfilet", "gemengde sla", "komkommer", "tomaat", "1 el olijfolie", "citroen"],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["gluten_free", "lactose_free", "high_protein"],
    allergens: [],
  },
  {
    id: "d-vegan-beans-veggies",
    mealType: "dinner",
    name: "Bonen + groenten bowl (zonder rijst)",
    calories: 470,
    protein: 22,
    carbs: 50,
    fat: 16,
    ingredients: ["zwarte bonen", "paprika", "ui", "tomaat", "kruiden", "limoen"],
    suitable_for: ["weight_loss", "maintenance"],
    tags: ["vegan", "vegetarian", "gluten_free", "lactose_free"],
    allergens: [],
  },

  // Snacks (6)
  {
    id: "s-protein-pudding",
    mealType: "snack",
    name: "Proteïne pudding",
    calories: 180,
    protein: 20,
    carbs: 14,
    fat: 4,
    ingredients: ["1 proteïne pudding (200g)"],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["vegetarian", "high_protein", "gluten_free"],
    allergens: ["lactose"],
  },
  {
    id: "s-apple-peanutbutter",
    mealType: "snack",
    name: "Appel + pindakaas",
    calories: 220,
    protein: 6,
    carbs: 24,
    fat: 12,
    ingredients: ["1 appel", "15g pindakaas"],
    suitable_for: ["maintenance", "muscle"],
    tags: ["vegan", "vegetarian", "gluten_free", "lactose_free"],
    allergens: ["nuts"],
  },
  {
    id: "s-skyr-berries",
    mealType: "snack",
    name: "Skyr + bessen",
    calories: 160,
    protein: 18,
    carbs: 16,
    fat: 1,
    ingredients: ["200g skyr", "100g bessen"],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["vegetarian", "high_protein", "gluten_free"],
    allergens: ["lactose"],
  },
  {
    id: "s-carrots-hummus",
    mealType: "snack",
    name: "Wortels + hummus",
    calories: 190,
    protein: 7,
    carbs: 20,
    fat: 9,
    ingredients: ["wortels", "70g hummus"],
    suitable_for: ["weight_loss", "maintenance"],
    tags: ["vegan", "vegetarian", "gluten_free", "lactose_free"],
    allergens: ["soy"],
  },
  {
    id: "s-rice-cakes-turkey",
    mealType: "snack",
    name: "Rijstwafels + kalkoen",
    calories: 210,
    protein: 18,
    carbs: 22,
    fat: 5,
    ingredients: ["3 rijstwafels", "80g kalkoenfilet"],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["gluten_free", "lactose_free", "high_protein"],
    allergens: [],
  },
  {
    id: "s-mixed-nuts",
    mealType: "snack",
    name: "Gemengde noten (handje)",
    calories: 210,
    protein: 7,
    carbs: 6,
    fat: 18,
    ingredients: ["30g gemengde noten"],
    suitable_for: ["maintenance", "muscle"],
    tags: ["vegan", "vegetarian", "gluten_free", "lactose_free"],
    allergens: ["nuts"],
  },
];

