import type { Recipe } from "@/lib/mealplanner/types";

export const recipes: Recipe[] = [
  // ─────────────────────────────────────────
  // BREAKFAST (regular)
  // ─────────────────────────────────────────
  {
    id: "b-overnight-oats-berry",
    mealType: "breakfast",
    name: "Overnight oats met bessen",
    calories: 420,
    protein: 28,
    carbs: 55,
    fat: 10,
    ingredients: ["60g havermout", "200ml (soja)melk", "150g bessen", "15g chiazaad", "1 tl kaneel"],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["vegetarian", "high_protein"],
    allergens: ["gluten", "soy"],
    imageKeyword: "overnight-oats-berries",
  },
  {
    id: "b-greek-yogurt-granola",
    mealType: "breakfast",
    name: "Griekse yoghurt bowl",
    calories: 380,
    protein: 32,
    carbs: 40,
    fat: 9,
    ingredients: ["250g Griekse yoghurt", "30g granola", "1 banaan", "1 tl honing"],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["vegetarian", "high_protein"],
    allergens: ["lactose", "gluten"],
    imageKeyword: "greek-yogurt-granola",
  },
  {
    id: "b-eggs-toast-avocado",
    mealType: "breakfast",
    name: "Roerei + volkoren toast + avocado",
    calories: 460,
    protein: 26,
    carbs: 36,
    fat: 22,
    ingredients: ["3 eieren", "2 sneetjes volkoren brood", "1/2 avocado", "peper & zout"],
    suitable_for: ["muscle", "maintenance"],
    tags: ["vegetarian", "high_protein"],
    allergens: ["egg", "gluten"],
    imageKeyword: "scrambled-eggs-avocado-toast",
  },
  {
    id: "b-protein-smoothie",
    mealType: "breakfast",
    name: "Proteïne smoothie (banaan + pindakaas)",
    calories: 520,
    protein: 40,
    carbs: 50,
    fat: 18,
    ingredients: ["1 banaan", "250ml (soja)melk", "30g proteïnepoeder", "15g pindakaas", "ijsblokjes"],
    suitable_for: ["muscle", "maintenance"],
    tags: ["vegetarian", "high_protein"],
    allergens: ["nuts", "soy", "lactose"],
    imageKeyword: "protein-smoothie-banana",
  },
  {
    id: "b-cottage-cheese-fruit",
    mealType: "breakfast",
    name: "Hüttenkäse met fruit",
    calories: 340,
    protein: 30,
    carbs: 32,
    fat: 8,
    ingredients: ["250g hüttenkäse", "1 appel of peer", "1 tl kaneel", "10g walnoten (optioneel)"],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["vegetarian", "high_protein"],
    allergens: ["lactose", "nuts"],
    imageKeyword: "cottage-cheese-fruit",
  },
  {
    id: "b-vegan-tofu-scramble",
    mealType: "breakfast",
    name: "Tofu scramble met groenten",
    calories: 390,
    protein: 26,
    carbs: 24,
    fat: 20,
    ingredients: ["200g tofu", "paprika", "spinazie", "kurkuma", "1 tl olijfolie"],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["vegan", "vegetarian", "high_protein", "gluten_free", "lactose_free"],
    allergens: ["soy"],
    imageKeyword: "tofu-scramble-vegetables",
  },
  {
    id: "b-rice-cakes-quark",
    mealType: "breakfast",
    name: "Rijstwafels met magere kwark",
    calories: 360,
    protein: 32,
    carbs: 44,
    fat: 6,
    ingredients: ["4 rijstwafels", "250g magere kwark", "aardbeien", "1 tl honing"],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["vegetarian", "high_protein", "gluten_free"],
    allergens: ["lactose"],
    imageKeyword: "rice-cakes-strawberry",
  },

  // ─────────────────────────────────────────
  // BREAKFAST (Proteïne)
  // ─────────────────────────────────────────
  {
    id: "b-f1-shake-chocolate",
    mealType: "breakfast",
    name: "Formula 1 Chocolade Shake",
    calories: 220,
    protein: 21,
    carbs: 28,
    fat: 3,
    ingredients: [
      "2 scoops (52g) Formula 1 Chocolade",
      "250ml halfvolle melk",
      "1 banaan (optioneel)",
      "ijsblokjes",
    ],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["vegetarian", "high_protein"],
    allergens: ["lactose", "soy"],
    premium: true,
    premiumProduct: "Proteïneshake Chocolade",
    imageKeyword: "chocolate-protein-shake",
  },
  {
    id: "b-f1-shake-vanilla-berry",
    mealType: "breakfast",
    name: "Formula 1 Vanille-Bessen Shake",
    calories: 240,
    protein: 21,
    carbs: 34,
    fat: 3,
    ingredients: [
      "2 scoops (52g) Formula 1 Vanille",
      "250ml (soja)melk",
      "100g gemengde bessen",
      "1 tl chiazaad",
    ],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["vegetarian", "high_protein"],
    allergens: ["lactose", "soy"],
    premium: true,
    premiumProduct: "Proteïneshake Vanille",
    imageKeyword: "vanilla-berry-smoothie",
  },
  {
    id: "b-f1-shake-strawberry-banana",
    mealType: "breakfast",
    name: "Formula 1 Aardbei-Banaan Shake",
    calories: 235,
    protein: 21,
    carbs: 32,
    fat: 3,
    ingredients: [
      "2 scoops (52g) Formula 1 Aardbei",
      "200ml amandelmelk",
      "1 kleine banaan",
      "ijsblokjes",
    ],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["vegetarian", "high_protein", "gluten_free"],
    allergens: ["soy"],
    premium: true,
    premiumProduct: "Proteïneshake Aardbei",
    imageKeyword: "strawberry-banana-smoothie",
  },
  {
    id: "b-herbal-tea-morning",
    mealType: "breakfast",
    name: "Herbal Tea Concentrate als ochtendboost",
    calories: 180,
    protein: 18,
    carbs: 22,
    fat: 2,
    ingredients: [
      "1 tl (1,7g) Herbal Tea Concentrate Original",
      "300ml warm water",
      "2 rijstwafels",
      "200g magere kwark",
      "fruit naar keuze",
    ],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["vegetarian", "high_protein", "gluten_free"],
    allergens: ["lactose"],
    premium: true,
    premiumProduct: "Kruidenthee",
    imageKeyword: "herbal-tea-morning-healthy",
  },

  // ─────────────────────────────────────────
  // LUNCH (regular)
  // ─────────────────────────────────────────
  {
    id: "l-chicken-wrap",
    mealType: "lunch",
    name: "Kip wrap + groentemix",
    calories: 540,
    protein: 42,
    carbs: 55,
    fat: 16,
    ingredients: ["2 wraps", "180g kipfilet", "sla", "tomaat", "komkommer", "yoghurtsaus"],
    suitable_for: ["muscle", "maintenance"],
    tags: ["high_protein"],
    allergens: ["gluten", "lactose"],
    imageKeyword: "chicken-wrap-vegetables",
  },
  {
    id: "l-tuna-salad-bowl",
    mealType: "lunch",
    name: "Tonijnsalade bowl",
    calories: 480,
    protein: 40,
    carbs: 35,
    fat: 18,
    ingredients: ["1 blik tonijn", "gemengde sla", "cherrytomaat", "maïs", "1 el olijfolie", "citroen"],
    suitable_for: ["weight_loss", "maintenance"],
    tags: ["gluten_free", "lactose_free", "high_protein"],
    allergens: ["fish"],
    imageKeyword: "tuna-salad-bowl",
  },
  {
    id: "l-veggie-burrito-bowl",
    mealType: "lunch",
    name: "Veggie burrito bowl",
    calories: 560,
    protein: 28,
    carbs: 78,
    fat: 14,
    ingredients: ["150g rijst", "150g kidneybonen", "paprika", "ui", "tomaat", "kruidenmix"],
    suitable_for: ["weight_loss", "maintenance"],
    tags: ["vegan", "vegetarian", "gluten_free", "lactose_free"],
    allergens: [],
    imageKeyword: "burrito-bowl-vegetables",
  },
  {
    id: "l-turkey-sandwich",
    mealType: "lunch",
    name: "Volkoren sandwich met kalkoen",
    calories: 510,
    protein: 38,
    carbs: 52,
    fat: 14,
    ingredients: ["3 sneetjes volkoren brood", "120g kalkoenfilet", "mosterd", "sla", "tomaat"],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["high_protein"],
    allergens: ["gluten"],
    imageKeyword: "turkey-sandwich-wholegrain",
  },
  {
    id: "l-salmon-quinoa",
    mealType: "lunch",
    name: "Zalm + quinoa + groenten",
    calories: 620,
    protein: 42,
    carbs: 55,
    fat: 24,
    ingredients: ["150g zalm", "120g quinoa", "broccoli", "citroen", "1 tl olijfolie"],
    suitable_for: ["muscle", "maintenance"],
    tags: ["gluten_free", "lactose_free", "high_protein"],
    allergens: ["fish"],
    imageKeyword: "salmon-quinoa-bowl",
  },
  {
    id: "l-egg-salad",
    mealType: "lunch",
    name: "Eiersalade + crackers",
    calories: 520,
    protein: 26,
    carbs: 40,
    fat: 26,
    ingredients: ["3 eieren", "2 el (light) mayo", "crackers", "sla", "paprika"],
    suitable_for: ["maintenance"],
    tags: ["vegetarian", "high_protein"],
    allergens: ["egg", "gluten"],
    imageKeyword: "egg-salad-crackers",
  },
  {
    id: "l-lentil-soup",
    mealType: "lunch",
    name: "Linzen soep + volkoren brood",
    calories: 520,
    protein: 26,
    carbs: 78,
    fat: 10,
    ingredients: ["linzen", "wortel", "ui", "selder", "bouillon", "2 sneetjes volkoren brood"],
    suitable_for: ["weight_loss", "maintenance"],
    tags: ["vegan", "vegetarian"],
    allergens: ["gluten"],
    imageKeyword: "lentil-soup-bowl",
  },
  {
    id: "l-chicken-rice-salad",
    mealType: "lunch",
    name: "Kip + rijstsalade",
    calories: 590,
    protein: 44,
    carbs: 70,
    fat: 14,
    ingredients: ["180g kipfilet", "150g rijst", "komkommer", "tomaat", "citroen", "kruiden"],
    suitable_for: ["muscle", "maintenance"],
    tags: ["gluten_free", "lactose_free", "high_protein"],
    allergens: [],
    imageKeyword: "chicken-rice-salad",
  },
  {
    id: "l-vegan-chickpea-salad",
    mealType: "lunch",
    name: "Kikkererwten salade + avocado",
    calories: 580,
    protein: 22,
    carbs: 62,
    fat: 26,
    ingredients: ["kikkererwten", "avocado", "tomaat", "komkommer", "citroen", "kruiden"],
    suitable_for: ["maintenance"],
    tags: ["vegan", "vegetarian", "gluten_free", "lactose_free"],
    allergens: [],
    imageKeyword: "chickpea-avocado-salad",
  },

  // ─────────────────────────────────────────
  // LUNCH (Proteïne)
  // ─────────────────────────────────────────
  {
    id: "l-f1-shake-lunch-cookies",
    mealType: "lunch",
    name: "Formula 1 Cookies & Cream Shake + salade",
    calories: 480,
    protein: 32,
    carbs: 44,
    fat: 10,
    ingredients: [
      "2 scoops (52g) Formula 1 Cookies & Cream",
      "250ml (soja)melk",
      "grote gemengde salade",
      "1 el olijfolie & citroen",
    ],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["vegetarian", "high_protein"],
    allergens: ["lactose", "soy", "gluten"],
    premium: true,
    premiumProduct: "Proteïneshake Cookies & Cream",
    imageKeyword: "cookies-cream-protein-shake",
  },
  {
    id: "l-aloe-lunch-bowl",
    mealType: "lunch",
    name: "Aloe Vera Drink + Kip & Quinoa bowl",
    calories: 560,
    protein: 42,
    carbs: 52,
    fat: 14,
    ingredients: [
      "15ml Aloe Vera Concentrate",
      "500ml water (aangelengd)",
      "180g kipfilet",
      "100g quinoa",
      "gemengde groenten",
    ],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["gluten_free", "lactose_free", "high_protein"],
    allergens: [],
    premium: true,
    premiumProduct: "Aloë vera drank",
    imageKeyword: "aloe-vera-drink-chicken-bowl",
  },

  // ─────────────────────────────────────────
  // DINNER (regular)
  // ─────────────────────────────────────────
  {
    id: "d-steak-veggies",
    mealType: "dinner",
    name: "Biefstuk + groene groenten",
    calories: 560,
    protein: 46,
    carbs: 18,
    fat: 32,
    ingredients: ["180g biefstuk", "boontjes", "sla of broccoli", "1 tl olijfolie", "kruiden"],
    suitable_for: ["muscle", "maintenance"],
    tags: ["gluten_free", "lactose_free", "high_protein"],
    allergens: [],
    imageKeyword: "grilled-steak-green-vegetables",
  },
  {
    id: "d-chicken-stir-fry",
    mealType: "dinner",
    name: "Kip roerbak met groenten",
    calories: 520,
    protein: 44,
    carbs: 26,
    fat: 24,
    ingredients: ["200g kipfilet", "wokgroenten", "sojasaus", "1 el sesamolie", "knoflook"],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["high_protein", "lactose_free"],
    allergens: ["soy"],
    imageKeyword: "chicken-stir-fry-vegetables",
  },
  {
    id: "d-salmon-asparagus",
    mealType: "dinner",
    name: "Zalm + asperges",
    calories: 540,
    protein: 40,
    carbs: 14,
    fat: 34,
    ingredients: ["170g zalm", "asperges", "citroen", "1 tl olijfolie", "dille"],
    suitable_for: ["weight_loss", "maintenance"],
    tags: ["gluten_free", "lactose_free", "high_protein"],
    allergens: ["fish"],
    imageKeyword: "grilled-salmon-asparagus",
  },
  {
    id: "d-turkey-chili",
    mealType: "dinner",
    name: "Kalkoen chili (zonder rijst)",
    calories: 510,
    protein: 44,
    carbs: 34,
    fat: 20,
    ingredients: ["200g kalkoengehakt", "tomatenblokjes", "kidneybonen", "paprika", "ui", "kruiden"],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["gluten_free", "lactose_free", "high_protein"],
    allergens: [],
    imageKeyword: "turkey-chili-healthy",
  },
  {
    id: "d-tofu-curry",
    mealType: "dinner",
    name: "Tofu curry + bloemkoolrijst",
    calories: 490,
    protein: 28,
    carbs: 28,
    fat: 26,
    ingredients: ["200g tofu", "curry pasta", "kokosmelk light", "wokgroenten", "bloemkoolrijst"],
    suitable_for: ["weight_loss", "maintenance"],
    tags: ["vegan", "vegetarian", "gluten_free", "lactose_free"],
    allergens: ["soy"],
    imageKeyword: "tofu-curry-cauliflower-rice",
  },
  {
    id: "d-omelet-veggies",
    mealType: "dinner",
    name: "Omelet met groenten",
    calories: 420,
    protein: 32,
    carbs: 16,
    fat: 26,
    ingredients: ["4 eieren", "champignons", "spinazie", "ui", "1 tl olijfolie"],
    suitable_for: ["weight_loss", "maintenance"],
    tags: ["vegetarian", "gluten_free", "high_protein"],
    allergens: ["egg"],
    imageKeyword: "vegetable-omelet",
  },
  {
    id: "d-cod-zoodles",
    mealType: "dinner",
    name: "Kabeljauw + courgetti",
    calories: 460,
    protein: 42,
    carbs: 18,
    fat: 22,
    ingredients: ["200g kabeljauw", "courgette", "tomatensaus", "knoflook", "1 tl olijfolie"],
    suitable_for: ["weight_loss", "maintenance"],
    tags: ["gluten_free", "lactose_free", "high_protein"],
    allergens: ["fish"],
    imageKeyword: "cod-zucchini-noodles",
  },
  {
    id: "d-chicken-salad",
    mealType: "dinner",
    name: "Kip salade (grote portie)",
    calories: 480,
    protein: 46,
    carbs: 20,
    fat: 22,
    ingredients: ["220g kipfilet", "gemengde sla", "komkommer", "tomaat", "1 el olijfolie", "citroen"],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["gluten_free", "lactose_free", "high_protein"],
    allergens: [],
    imageKeyword: "grilled-chicken-salad",
  },
  {
    id: "d-vegan-beans-veggies",
    mealType: "dinner",
    name: "Bonen + groenten bowl (zonder rijst)",
    calories: 470,
    protein: 22,
    carbs: 50,
    fat: 16,
    ingredients: ["zwarte bonen", "paprika", "ui", "tomaat", "kruiden", "limoen"],
    suitable_for: ["weight_loss", "maintenance"],
    tags: ["vegan", "vegetarian", "gluten_free", "lactose_free"],
    allergens: [],
    imageKeyword: "black-bean-vegetable-bowl",
  },

  // ─────────────────────────────────────────
  // SNACKS (regular)
  // ─────────────────────────────────────────
  {
    id: "s-protein-pudding",
    mealType: "snack",
    name: "Proteïne pudding",
    calories: 180,
    protein: 20,
    carbs: 14,
    fat: 4,
    ingredients: ["1 proteïne pudding (200g)"],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["vegetarian", "high_protein", "gluten_free"],
    allergens: ["lactose"],
    imageKeyword: "protein-pudding",
  },
  {
    id: "s-apple-peanutbutter",
    mealType: "snack",
    name: "Appel + pindakaas",
    calories: 220,
    protein: 6,
    carbs: 24,
    fat: 12,
    ingredients: ["1 appel", "15g pindakaas"],
    suitable_for: ["maintenance", "muscle"],
    tags: ["vegan", "vegetarian", "gluten_free", "lactose_free"],
    allergens: ["nuts"],
    imageKeyword: "apple-peanut-butter-snack",
  },
  {
    id: "s-skyr-berries",
    mealType: "snack",
    name: "Skyr + bessen",
    calories: 160,
    protein: 18,
    carbs: 16,
    fat: 1,
    ingredients: ["200g skyr", "100g bessen"],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["vegetarian", "high_protein", "gluten_free"],
    allergens: ["lactose"],
    imageKeyword: "skyr-berries-yogurt",
  },
  {
    id: "s-carrots-hummus",
    mealType: "snack",
    name: "Wortels + hummus",
    calories: 190,
    protein: 7,
    carbs: 20,
    fat: 9,
    ingredients: ["wortels", "70g hummus"],
    suitable_for: ["weight_loss", "maintenance"],
    tags: ["vegan", "vegetarian", "gluten_free", "lactose_free"],
    allergens: ["soy"],
    imageKeyword: "carrots-hummus-snack",
  },
  {
    id: "s-rice-cakes-turkey",
    mealType: "snack",
    name: "Rijstwafels + kalkoen",
    calories: 210,
    protein: 18,
    carbs: 22,
    fat: 5,
    ingredients: ["3 rijstwafels", "80g kalkoenfilet"],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["gluten_free", "lactose_free", "high_protein"],
    allergens: [],
    imageKeyword: "rice-cakes-turkey-snack",
  },
  {
    id: "s-mixed-nuts",
    mealType: "snack",
    name: "Gemengde noten (handje)",
    calories: 210,
    protein: 7,
    carbs: 6,
    fat: 18,
    ingredients: ["30g gemengde noten"],
    suitable_for: ["maintenance", "muscle"],
    tags: ["vegan", "vegetarian", "gluten_free", "lactose_free"],
    allergens: ["nuts"],
    imageKeyword: "mixed-nuts-healthy",
  },

  // ─────────────────────────────────────────
  // SNACKS (Proteïne)
  // ─────────────────────────────────────────
  {
    id: "s-premium-protein-bar",
    mealType: "snack",
    name: "Proteïnereep",
    calories: 210,
    protein: 21,
    carbs: 22,
    fat: 6,
    ingredients: ["1 Proteïnereep (60g) — Chocolate Chip Cookie Dough"],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["vegetarian", "high_protein"],
    allergens: ["gluten", "soy", "nuts"],
    premium: true,
    premiumProduct: "Proteïnereep",
    imageKeyword: "protein-bar-chocolate",
  },
  {
    id: "s-herbal-tea-snack",
    mealType: "snack",
    name: "Herbal Tea + rijstwafels",
    calories: 120,
    protein: 3,
    carbs: 22,
    fat: 2,
    ingredients: [
      "1 tl (1,7g) Herbal Tea Concentrate",
      "300ml warm water",
      "2 rijstwafels",
    ],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["vegan", "vegetarian", "gluten_free", "lactose_free"],
    allergens: [],
    premium: true,
    premiumProduct: "Kruidenthee",
    imageKeyword: "herbal-tea-rice-cakes",
  },
  {
    id: "s-aloe-vera-drink",
    mealType: "snack",
    name: "Aloe Vera Detox Drink",
    calories: 80,
    protein: 5,
    carbs: 10,
    fat: 1,
    ingredients: [
      "15ml Aloe Vera Concentrate",
      "400ml water",
      "citroensap (naar smaak)",
      "evt. 1 tl honing",
    ],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["vegan", "vegetarian", "gluten_free", "lactose_free"],
    allergens: [],
    premium: true,
    premiumProduct: "Aloë vera drank",
    imageKeyword: "aloe-vera-detox-drink",
  },
  {
    id: "s-pdm-shake-snack",
    mealType: "snack",
    name: "Protein Drink Mix snack shake",
    calories: 180,
    protein: 22,
    carbs: 14,
    fat: 3,
    ingredients: [
      "28g Protein Drink Mix Vanille",
      "200ml water of magere melk",
      "enkele ijsblokjes",
    ],
    suitable_for: ["weight_loss", "muscle", "maintenance"],
    tags: ["vegetarian", "high_protein", "gluten_free"],
    allergens: ["lactose", "soy"],
    premium: true,
    premiumProduct: "Eiwitdrank",
    imageKeyword: "vanilla-protein-shake",
  },
];
